valohai/valohai-cli

- valohai_cli/commands/execution/logs.py
This should fix some closely output events being dropped
> Hash events to figure out event IDs

- circle.yml
- tox.ini
- valohai_cli/commands/execution/run.py
- valohai_cli/git.py
- valohai_cli/models/project.py
This lays some groundwork for future additions.
> More small improvements and groundwork

- .gitignore
- circle.yml
- tests/commands/test_parcel.py
- valohai_cli/commands/parcel.py
- valohai_cli/tui.py
- valohai_cli/utils.py
This PR adds a brand-spankin'-new `parcel` command, which creates a self-contained copy of the project and its dependencies.
> Add parcel command

- valohai_cli/adhoc.py
Caused problems on Windows.
```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\User\\AppData\\Local\\Temp\\valohai-cli-vgw2odt1.tgz'
```
> Actually close temp adhoc tarball file before continuing

- valohai_cli/yaml_wizard.py
> Load image suggestions from valohai/images

- valohai_cli/commands/execution/info.py
- valohai_cli/commands/execution/logs.py
- valohai_cli/commands/execution/open.py
- valohai_cli/commands/execution/outputs.py
- valohai_cli/commands/execution/stop.py
- valohai_cli/commands/execution/watch.py
- valohai_cli/help_texts.py
- valohai_cli/models/project.py
- valohai_cli/utils/cli_utils.py
This depends on as-of-yet unreleased backend support though.
> Teach (almost all) execution-related commands about a special 'latest' counter value

- valohai_cli/commands/execution/run.py
Also add -i for shorter version of --image
> Add --title to execution parameters

- valohai_cli/commands/execution/run.py
> Move ad-hoc packaging after all input validation

- valohai_cli/packager.py
> Don't attempt to package files that do not exist

- valohai_cli/commands/execution/watch.py
We weren't catching all the errors we were supposed to.
Refs #40
> Make watch even more robust

- valohai_cli/commands/environments.py
> Add --gpu flag for vh environments to show GPU specifications (fixes #55)

- tests/commands/execution/test_run.py
- valohai_cli/commands/execution/run.py
- valohai_cli/commands/login.py
- valohai_cli/messages.py
- valohai_cli/models/project.py
Some small fixes and refactorings extracted from the forthcoming API driver PR.
> Some small fixes

- tests/commands/execution/test_outputs.py
- tests/commands/execution/utils.py
- tests/fixture_data.py
- valohai_cli/commands/environments.py
- valohai_cli/commands/execution/list.py
- valohai_cli/commands/execution/outputs.py
- valohai_cli/commands/init.py
- valohai_cli/table.py
- valohai_cli/yaml_wizard.py
A bunch of small bugfixes and improvements!
> Summer fixies 🏝

- valohai_cli/packager.py
> Fall back to non-git packaging if git ls-files fails

- .coveragerc
- tests/test_utils.py
- valohai_cli/_vendor/tabulate.py
- valohai_cli/table.py
> Use tabulate for table printing

- tests/test_packaging.py
- valohai_cli/cli.py
- valohai_cli/commands/execution/delete.py
- valohai_cli/commands/execution/info.py
- valohai_cli/commands/execution/list.py
- valohai_cli/commands/execution/outputs.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
- valohai_cli/commands/execution/stop.py
- valohai_cli/commands/lint.py
- valohai_cli/commands/login.py
- valohai_cli/commands/logout.py
- valohai_cli/commands/parcel.py
- valohai_cli/commands/project/create.py
- valohai_cli/commands/project/fetch.py
- valohai_cli/commands/project/unlink.py
- valohai_cli/messages.py
- valohai_cli/packager.py
- valohai_cli/settings/__init__.py
- valohai_cli/table.py
> Machine-readability fixes

- tests/commands/execution/run_test_utils.py
- tests/commands/execution/test_run.py
- tests/commands/test_parcel.py
- tests/fixture_data.py
- tests/test_remote_project.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
- valohai_cli/utils/file_input.py
Support using parameter files like the /valohai/config/parameters.json file as input (see #86).
Some QOL fixes too :)
> Parameter file support

- setup.py
> Pin to valohai-yaml>=0.9

- tests/commands/test_auth.py
- valohai_cli/commands/login.py
Passing `--token` to `vh login` will just verify that token and save it.
Fixes #94
> Login with token

- tests/commands/execution/run_test_utils.py
Fix adhoc tests not having been run since 2313d6c028b4
> Ad-hoc test regression

- tests/commands/project/utils.py
- tests/commands/test_init.py
- valohai_cli/commands/project/create.py
- valohai_cli/utils/__init__.py
> Add --owner to project creation

- valohai_cli/messages.py
> Disable emoji on Windows

- tests/commands/execution/run_test_utils.py
- tests/commands/execution/test_run.py
- tests/conftest.py
- tests/fixture_data.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
Correct coercion for flag-type parameters was quite absent. This adds some.
> Improve support for flag-type parameters

- DEVELOPMENT.md
As it says on the 🥫: add note about Python versions.
> Add info of versions to development notes

- TUTORIAL.md
- tests/commands/execution/test_run.py
- tests/commands/pipeline/test_run.py
- tests/commands/run_test_utils.py
- tests/fixture_data.py
- tests/test_remote_project.py
- valohai_cli/commands/execution/run/utils.py
- valohai_cli/commands/pipeline/__init__.py
- valohai_cli/commands/pipeline/run/__init__.py
- valohai_cli/commands/pipeline/run/run.py
- valohai_cli/commands/pipeline/run/utils.py
- valohai_cli/exceptions.py
- Add possibility to kick off a pipeline run by it's name completely based on the `valohai.yaml` configuration default values
Fixes #125
> Pipeline runs

- requirements-dev.txt
- scripts/ensure_click_help.py
- setup.py
- tests/commands/run_test_utils.py
- tests/commands/test_auth.py
- tests/test_git.py
- tests/test_packaging.py
- tests/test_utils.py
- valohai_cli/api.py
- valohai_cli/commands/execution/info.py
- valohai_cli/commands/execution/logs.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
- valohai_cli/commands/parcel.py
- valohai_cli/commands/project/link.py
- valohai_cli/exceptions.py
- valohai_cli/messages.py
- valohai_cli/models/project.py
- valohai_cli/plugin_cli.py
- valohai_cli/range.py
- valohai_cli/settings/persistence.py
- valohai_cli/table.py
- valohai_cli/utils/__init__.py
- valohai_cli/utils/cli_utils.py
- valohai_cli/utils/file_input.py
- valohai_cli/utils/file_size_format.py
- valohai_cli/utils/friendly_option_parser.py
Some of these changes could have been done around #64 / #106, but better late than never, I guess...
> Run Pyupgrade, drop six dependency

- tests/commands/execution/test_run.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
- valohai_cli/commands/execution/run/frontend_command.py
> Add --tag to `vh exec run`

- setup.py
- tests/commands/test_yaml.py
- tests/commands/yaml/test_yaml.py
- tests/fixture_data.py
- valohai_cli/commands/yaml.py
- valohai_cli/commands/yaml/__init__.py
- valohai_cli/commands/yaml/step.py
Use `vh yaml step myfile.py` to generate/update the active `valohai.yaml`
> New `vh yaml` command to generate/update configs based on .py source

- valohai_cli/packager.py
Cc @johncharrington, who's using a variation of this code right now :)
> Package files from submodules too

- valohai_cli/commands/yaml/step.py
Fixes valohai/valohai-utils#64
> Notify the user if a project is missing in vh yaml

- valohai_cli/api.py
- valohai_cli/commands/login.py
- valohai_cli/settings/__init__.py
> Allow disabling SSL verification when logging in

- tests/commands/execution/test_stop.py
- valohai_cli/commands/execution/stop.py
It had never actually worked.
Fixes #164
> Make `vh exec stop latest` work

- valohai_cli/yaml_wizard.py
> Use images.v2.yaml instead of legacy images.yaml

- tests/commands/alias/test_list.py
- tests/commands/data/test_list.py
- tests/fixture_data.py
- valohai_cli/commands/alias/__init__.py
- valohai_cli/commands/alias/list.py
- valohai_cli/commands/data/__init__.py
- valohai_cli/commands/data/list.py
fixes [#196](https://github.com/valohai/valohai-cli/issues/196)
In a linked project directory, you can read datums using `vh data list` or from specific project by `vh --project <project-id> data list`
**Columns**
* Name: The name of a datum 
* Size: The file size of a datum
* Output of Exec: The execution that a datum came from
* Created At: The time when a datum was created
* URL: datum:// url to use as an input for execution for example
* URI: Storage uri for the file that a datum is pointing.
```text
Name                        Size     Output of Exec  Created At                   URL                                           URI                                                                                    
--------------------------  -------  -------------- …
```
> Add data and alias command to fetch Datums and Datum Aliases

- tests/commands/deployment/test_create_version.py
- tests/commands/run_test_utils.py
- tests/fixture_data.py
- valohai_cli/commands/deployment/__init__.py
- valohai_cli/commands/deployment/create_version/__init__.py
- valohai_cli/commands/deployment/create_version/create_version.py
- valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
> Deployment version creation

- valohai_cli/commands/execution/run/dynamic_run_command.py
- valohai_cli/commands/execution/run/frontend_command.py
It's like `--watch`, but with more WWW!
> Add --open-browser option to `exec run`

- valohai_cli/adhoc.py
- valohai_cli/utils/api_error_utils.py
> Validate commit in respect to the active project

- valohai_cli/commands/project/create.py
- valohai_cli/commands/project/link.py
> Allow selecting an owner for the new project

- setup.cfg
> Bump valohai* deps to their current freshest versions

- README.md
> Update readme to mention pipx as preferred system-wide install

- valohai_cli/commands/pipeline/run/run.py
> Allow tagging pipelines

- .github/workflows/ci.yml
> CI: publish to PyPI too

- valohai_cli/commands/execution/list.py
Add option to list only deleted executions
> List only deleted executions

- valohai_cli/commands/execution/list.py
Allow listing only my executions from a project
> Add option to list only my executions

- README.md
> Correct CI badge URL

- tests/commands/pipeline/test_run.py
- tests/commands/run_test_utils.py
- tests/fixture_data.py
- valohai_cli/commands/pipeline/run/run.py
Resolves #284  
To add overriding of pipeline parameters
- Override function added
- Test added
> Pipeline parameters overriding

- tests/fixture_data.py
- tests/test_remote_project.py
- valohai_cli/commands/pipeline/run/run.py
Solves #280
- add commit_identifier if project is remote
- add tests
> Add commit_identifier in pipeline's run

- .pre-commit-config.yaml
- pyproject.toml
- valohai_cli/commands/deployment/create_version/dynamic_creation_command.py
- valohai_cli/commands/execution/list.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/commands/pipeline/run/run.py
- valohai_cli/settings/__init__.py
> Update pre-commit tools, add more Ruff rules, fix 'em

- tests/commands/execution/test_run.py
- valohai_cli/commands/execution/run/frontend_command.py
> Allow `--priority` for implicit high priority

- valohai_cli/commands/environments.py
> Environments command: Request unfinished job count 

- .github/workflows/ci.yml
Make sure everything works with the latest official release.
Should not cause anything to break.
> Add python 3.13 to the test suite

- tests/commands/notebook/test_notebook_execution_run.py
- tests/commands/run_test_utils.py
- valohai_cli/commands/notebook/run/run.py
- valohai_cli/plugin_cli.py
Follow-up on #334 to make it one smidgeon less minimal 😄
> notebook run: add support for environment variables
