- tests/commands/execution/test_logs.py
- tests/commands/execution/utils.py
- tests/fixture_data.py
- valohai_cli/commands/execution/logs.py
- valohai_cli/commands/execution/watch.py
- valohai_cli/log_manager.py
* Refactor common logic to LogManager
* Teach `vh exec logs` about limits and `--all`
* Make `vh exec watch` read less events
> Teach log commands about the new events endpoint

- valohai_cli/commands/environments.py
- valohai_cli/commands/project/link.py
- valohai_cli/commands/project/list.py
Based on http://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination, `limit` is used as a query parameter instead of `count`.
Before:
```
https://app.valohai.com/api/v0/environments/?count=1
```
After:
```
https://app.valohai.com/api/v0/environments/?limit=1
```
> Change non existent count parameter to limit

- valohai_cli/consts.py
Turns stderr into the much more zen yellow we use in the webapp.
> Recolor stderr

- valohai_cli/commands/execution/outputs.py
- valohai_cli/commands/execution/run.py
Example commands:
Download and keep waiting for output files of latest execution
`vh outputs latest --sync --download=myfolder`
Start a new execution and keep waiting for output files
`vh execution run train --sync=myfolder`
> Add ability to sync/download execution outputs live 

- README.md
- valohai_cli/cli.py
We're not yet fully dropping support though, just not mentioning it in the readme anymore.
Refs #64
> Add a warning about future versions dropping Py2 support

- tests/test_errors.py
- valohai_cli/api.py
- valohai_cli/commands/execution/run.py
- valohai_cli/commands/execution/run/__init__.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
- valohai_cli/commands/execution/run/excs.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/commands/execution/run/utils.py
- valohai_cli/exceptions.py
- valohai_cli/utils/api_error_utils.py
- valohai_cli/utils/error_fmt.py
Now that API errors are actual dicts with error codes and all, we can 
* format them in a human-readable way
* dig actionable hints out of them
Closes #61 (supersedes it)
Fixes valohai/roi#987
> Embetter error formatting

- setup.py
We need the show_envvar kwarg since 1a0f77b33150c02648652e793974f0312a17e7d7.
It was added in pallets/click#710 and released in Click 7.0.
> Correct click version requirement to >= 7.0

- valohai_cli/adhoc.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/packager.py
This adds an inner `package_files_into` function that can be used by software using `valohai-cli` as a library to further customize the contents of an ad-hoc tarball.
> Refactor package_directory function

- valohai_cli/commands/login.py
- valohai_cli/exceptions.py
- valohai_cli/messages.py
When we can't use "keyboard-interactive" authentication, e.g. when the user has 2FA or an external identity, we'll show them an instructive 3-step guide instead.
> Instruct users about token login

- valohai_cli/commands/login.py
Turns out `--valohai-host` was never respected by `vh login`.
> Support --valohai-host in `login` too

- valohai_cli/commands/execution/run/dynamic_run_command.py
Without this fix, any `valohai.yaml` that has an input with a list of URIs as default fails.
This is because the CLI puts an extra nested array in the payload.
valohai.yaml (without list)
```
inputs:
- default: https://herp.com/training_v2.csv
```
Resulting CLI payload:
```
'inputs': {'training': ('https://herp.com/training_v2.csv',)}
```
valohai.yaml (default is a list)
```
inputs:
- default:
- https://herp.com/training_v2.csv
```
Resulting CLI payload:
```
{'inputs': {'training': (['https://herp.com/training_v2.csv'],)}}
```
Fails crypticly with:
```
TypeError: argument of type 'NoneType' is not iterable
```
> Fix parsing for inputs with a list of defaults

- valohai_cli/settings/persistence.py
When saving a config file for the first time, try making it readable only by the user.
This is done only when the file doesn't pre-exist, to make it possible for users to manually make the file more readable should they require that.
> Chmod persistence file

- valohai_cli/commands/yaml/step.py
Updating `yaml step` command to make sure `valohai-utils` in is the requirements.txt.
Add a requirements.txt when creating a new step, if there isn't one already
If there is a requirements.txt already, append valohai-utils
> Add valohai-utils to requirements.txt

- tests/commands/execution/test_run.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/commands/init.py
- valohai_cli/commands/parcel.py
- valohai_cli/table.py
- valohai_cli/tui.py
Replace grave accents with quotes in printed help, as it causes issues with reStructuredText used to generate Valohai's official documentation.
> Replace grave accents with quotes

- valohai_cli/commands/yaml/step.py
Valohai CLI was accidentally using the default merge strategy for configs when calling `vh yaml step` command, which is too aggressive when merging with the existing step config.
> Use the correct merge strategy for vh yaml step (fixes #149)

- tests/commands/test_auth.py
- valohai_cli/commands/login.py
With this PR:
* login will ask to verify the login host; one can just hit ENTER to accept the default (app.valohai.com, or whatever had been overridden using the `VALOHAI_HOST` envvar)
* login will not fail if the host (either via arg or interactive prompt) is malformed (not a real base URL)
Fixes #151
> Embetter login host prompt flow

- valohai_cli/commands/yaml/pipeline.py
This PR:
* fixes some miscellaneous error messages in the pipeline... pipeline
* makes it so that the pipeline-generating code is only executed once per file (my previous pull request review hadn't taken that into consideration)
* catches exceptions from the pipeline-generating code to prefix them with some context (pending valohai/papi#9 to make the errors even better), see below. (#156)
```
$ vh yaml pipe xx.py
😢  ERROR: Retrieving a new pipeline definition for project asdf-pipeline-demo for xx.py failed.
The configuration file in use is /Users/akx/build/tensorflow-example/valohai.yaml. See the full traceback below.
Traceback (most recent call last):
[...]
File "xx.py", line 8, in main
extract = pipe.execution("Batch feature extraction")
File "papi/__init__.py", line 40, in execution …
```
> Pipeline fixes

- setup.py
- tests/commands/execution/test_run.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/commands/pipeline/run/run.py
- valohai_cli/commands/pipeline/run/utils.py
- valohai_cli/models/project.py
This PR:
* bumps the required minimum versions of the valohai-* packages to somewhat newer versions
* increases test compatibility with newer versions of Click that have changed some spellings
* fixes some type errors found by `mypy --strict`
> Version bumps & type fixes

- valohai_cli/commands/pipeline/run/utils.py
The issue is nicely explained in #160
> Make optional inputs without default work for pipeline runs (fixes #160)

- tests/test_settings.py
- valohai_cli/api.py
- valohai_cli/commands/yaml/step.py
- valohai_cli/settings/__init__.py
This allows downstream library users to modify the user-agent reported by valohai-cli without having to override, like, everything.
> Add transient setting `api_user_agent_prefix`

- setup.cfg
- valohai_cli/commands/pipeline/run/run.py
- valohai_cli/commands/pipeline/run/utils.py
Following https://github.com/valohai/valohai-yaml/pull/61, valohai-yaml has the canonical code to convert a pipeline definition to a payload.
> Use valohai-yaml for pipeline payload generation

- tests/test_table.py
- valohai_cli/table.py
Regressed presumably in 6a46ebff24f4959eb42c1d2c3b49376a8a06b026.
Draft since this builds on #187.
> Fix formatting for *SV output

- tests/commands/execution/test_run.py
- tests/commands/project/utils.py
- tests/commands/run_test_utils.py
- tests/commands/yaml/test_step.py
- tests/conftest.py
- tests/test_packaging.py
- valohai_cli/adhoc.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/commands/lint.py
- valohai_cli/commands/yaml/step.py
- valohai_cli/models/project.py
- valohai_cli/packager.py
- When creating an adhoc commit, ask roi what the yaml path of that project is and send that path over to `import_package` in roi
Fixes valohai/roi#3953
> Allow creating adhoc commits with a nonstandard yaml path

- tests/commands/execution/test_run.py
- tests/commands/pipeline/test_run.py
- tests/commands/run_test_utils.py
- tests/commands/yaml/test_pipeline.py
- tests/commands/yaml/test_step.py
- tests/commands/yaml/utils.py
- valohai_cli/adhoc.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/commands/pipeline/run/run.py
- valohai_cli/commands/yaml/pipeline.py
- valohai_cli/commands/yaml/step.py
- valohai_cli/models/project.py
- valohai_cli/models/remote_project.py
- valohai_cli/utils/commits.py
Fixes #193
Add an option `--yaml` to exec, pipeline and yaml creation in order to specify a custom config path.
> Allow custom yaml paths when adhocing

- valohai_cli/models/project.py
When creating a new project via `vh init` the project doesn't have a connected repository in valohai, so the yaml path in the project data is also set as `None`. Let's always make it default to `valohai.yaml`.
> Default to valohai.yaml properly when path in project data is None

- valohai_cli/adhoc.py
Since `create_adhoc_commit_from_tarball` is being used in jupyhai which isn't aware of custom yaml paths per command, only make yaml_path mandatory in the following private `_upload_commit_code` function and use the project settings yaml as default.
(Also came across a comment to delete a compatibility alias in 2020 so I did.)
Fixes #194
> Keep create_adhoc_commit_from_tarball in tact

- setup.cfg
These changes will make the PyPI page more helpful after the next release.
The current information is pretty slim:
> Add description values to package metadata

- valohai_cli/packager.py
If files are existing in git but not on disk (deleted files), simply ignore them when packaging.
Fixes valohai/roi#4177
> Ignore missing files during packaging

- tests/commands/execution/test_run.py
- valohai_cli/commands/execution/run/frontend_command.py
Allow passing `--autorestart_spot` or `-r` when using the spot instances
Fixes #208
> Spot restart

- tests/commands/execution/test_run.py
- tests/fixture_data.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
Fixes #211
Multiple styled parameter will now be transferred as an array if such value. See more info in the issue #211.
> Execution run command: handle multiple-styled parameters

- .github/dependabot.yml
Refs #216, #217 – let's see if Dependabot can keep us up to date.
See https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
> Create dependabot.yml for version bumps

- valohai_cli/commands/yaml/step.py
Quickfix.. if a customer has a requirements.txt that doesn't end with an empty line we'll append valohai-utils to the end of the last line, instead of creating a new one
```
torch==1.13.0
torchvision==0.14.0
```
There's probably a smorter way to do this :shrug:
> add linebreak before adding valohai-utils to requirements.txt

- Makefile
- README.md
Slight improvements to `make` targets and README developer guide.
I first tried running the development tooling with Python 3.7 (`mypy` fails to install the listed version) and then 3.8 (type checks give false positives) and jumped to Python 3.10 (based on version used by the CI) which works fine~~
Noted that down in the README.
> 🧑‍💻🔨 Improve developer experience

- tests/commands/deployment/test_create_version.py
- tests/commands/execution/test_run.py
- tests/test_utils_commits.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/models/project.py
- valohai_cli/utils/commits.py
Valohai commit identifiers are not always git SHAs; they can have YAML path extension.
So using e.g. `vh exec run` in local mode could ask for a commit identifier by git SHA, but the API only lists one with the extension attached. This is a bug 🐛
Allow partial commit identifier matches as `valohai-cli` doesn't know the exact format of the identifiers generated by the API, although the YAML path is generally available.
Tested through the `resolve_commit` helper for slightly better test coverage 🧪
Fixes #241
> 🐛 Allow partial matches when resolving commits

- README.md
`pipx valohai-cli` fails with invalid choice for argument command, it requires `pipx install valohai-cli` to work properly.
> Fix pipx install command in readme

- valohai_cli/commands/login.py
The trailing slash is optional when using custom host, but token generation URL format expects it.
Fixed
> Add missing slash into authtoken url

- tests/commands/pipeline/test_run.py
- tests/conftest.py
- valohai_cli/commands/pipeline/run/run.py
Resolves https://github.com/valohai/roi/issues/5071. 
During `vh pipeline run <pipeline> --adhoc`, pipeline steps were resolved on CLI end without honouring the `--yaml` flag for custom configuration. Project default configuration file's steps were used always. We shall now honour the flag. 
This behaviour has an existing test case and the tested code raised an exception as it did not find the default configuration file. However, the default test runner catches exceptions and the test case did not check that the command finished with a successful exit code, nor expected enough output to determine success. These oversights allowed the test to succeed. We will now reraise any exceptions raised during command tests, and pipeline tests will positively assert success up to the API response. …
> Honour --yaml flag to parse configuration in vh pipeline run --adhoc

- README.md
Old Make recipies have been replaced with pre-commit.
Bring the README up to date with the current configuration.
(Current actions copied from the yaml repo README.)
> Update lint & test instructions

- Makefile
- README.md
Linting still done with pre-commit under the hood. Add pre-commit installation to `make dev` so that a separate installation step is not needed.
> Create a make recipe to run lint

- pyproject.toml
Includes pipeline parameter conversion function needed for https://github.com/valohai/valohai-cli/pull/285
> Require `valohai-yaml>=0.31.0`

- .github/workflows/ci.yml
- DEVELOPMENT.md
- README.md
- pyproject.toml
- valohai_cli/ctx.py
Drops the typing-extensions requirement too.
> Require Python 3.8+

- pyproject.toml
- tests/test_cli_descriptions.py
- valohai_cli/commands/parcel.py
- valohai_cli/commands/update_check.py
- valohai_cli/consts.py
- valohai_cli/plugin_cli.py
The clever idea to use an ExceptionGroup (the other option having been [pytest-check](https://pypi.org/project/pytest-check/)) was courtesy of tpr at koodiklinikka.
Also, turns out the original #279 bug was just a matter of newline padding in the help string; `get_short_help_str` had been added to Click only some time after I'd written the original plugin CLI code, so no wonder we hadn't used it: https://github.com/pallets/click/pull/869
Click 8 is required for `to_info_dict`: https://github.com/pallets/click/pull/1623
> Ensure help texts are shown (and all commands have them)

- tests/test_utils_commits.py
- valohai_cli/api.py
- valohai_cli/utils/commits.py
Resolves #254 
#Why does this pull request exists?
When there is new commits in git repository, cli wont fetch the latest commits and abort by declaring the commit unknown.
##Changes made in PR:
- Fetch latest details when a commit is unknown
- Modified tests according to the case
> Add `fetch commits` functionality in case of unknown commit

- tests/commands/execution/test_run.py
- tests/commands/run_test_utils.py
- tests/fixture_data.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/utils/__init__.py
Included in this PR:
===
1. Parse Kubernetes `resource` structure from YAML when using `vh execution run`, if provided.
2. Parse Kubernetes resource claims directly as `vh execution run` command line arguments
`vh pipeline run` does not have execution runtime option override support for now.
> Kubernetes step parsing and command line options

- valohai_cli/api.py
- valohai_cli/exceptions.py
This will make catching these easier in downstream projects like Jupyhai.
> Give API connection errors a specific exception class

- pyproject.toml
A newer version is required to run tests
(`execution/test_run` fails with too old yaml package).
> Bump `valohai_yaml` to `0.38.0` to support runtime configs

- tests/commands/execution/test_run.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
- valohai_cli/commands/execution/run/frontend_command.py
Resolves #303 
Allow setting a preset ID with the `--k8s-preset` command line option.
Note: preset slug support will be automatic once that has been added to the API – no functional changes required (though the help text should be updated).
_Note:_ The first commit contains all the functional changes in this PR – the rest are just refactoring and tidying up the code a bit. Especially the last one is things that are more a matter of taste (and can be reverted easily).
> Add command line parameter for runtime config preset

- Makefile
Install and update dependencies with `uv`, fall back to regular `pip`.
Both work if virtual environment was created with `venv` or `virtualenv`.
Add requirement for an active virtual environment before installing packages to prevent accidentally updating a global Python installation.
> Use `uv` for dependencies if installed

- valohai_cli/commands/login.py
- valohai_cli/messages.py
Instead of telling the user to run a command to log in with the token they generate, we ask for it interactively.
Fixes #307.
In lieu of a screenshot...
```
$ vh login --host https://valohai.local/
If you don't yet have an account, please create one at https://valohai.local/ first.
https://valohai.local/ - Username: 2faman
2faman on https://valohai.local/ - Password: [...]
Retrieving API token from https://valohai.local/...
======================================================================================
Oops!
The error code "has_2fa" indicates username + password authentication is not possible.
Use a login token instead:
1. Log in on https://valohai.local/
2. Visit https://valohai.local/auth/tokens/ to generate an authentication token
3. Once you have an authentication token, paste …
```
> Smoother token login flow

- pyproject.toml
- tests/commands/pipeline/test_run.py
- tests/commands/run_test_utils.py
- tests/fixture_data.py
- tests/test_remote_project.py
- valohai_cli/commands/pipeline/run/run.py
Extends pipeline command line parameter parsing to allow overriding the default pipeline parameters with a list parameter
Upgrades `valohai-yaml` dependency to 0.40.0 containing list-type pipeline parameter support as well as override support in PipelineConverter which we will pass any command line overrides to
> Support list parameters for pipelines

- tests/commands/execution/test_run.py
- valohai_cli/adhoc.py
- valohai_cli/commands/deployment/create_version/create_version.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/commands/pipeline/run/run.py
- valohai_cli/packager.py
- valohai_cli/utils/commits.py
> option to disable git packaging for adhoc execution

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- scripts/ensure_click_help.py
- tests/test_cli_descriptions.py
`build` would fail due to an outdated upload action. Might as well upgrade everything else.
> Upgrade lint and CI tools

- tests/commands/execution/test_ssh.py
- tests/commands/execution/test_watch.py
- tests/commands/execution/utils.py
- tests/fixture_data.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
- valohai_cli/commands/execution/run/frontend_command.py
- valohai_cli/commands/execution/ssh.py
- valohai_cli/settings/paths.py
- valohai_cli/utils/__init__.py
- valohai_cli/utils/ssh.py
Resolves #312 
User will be able to remotely debug the execution 
1. He can either provide address:port & private key by himself or run the command for auto collection of the details
2. If the key is generated in CLI while starting the execution it can be found by command and prompted to user as option 
3. But if the execution is started by UI or key is generated somewhere user HAS to provide that key as command argument `--private-key-file `
[ssh.webm](https://github.com/user-attachments/assets/ec4c3d48-5bb8-4f48-9a88-a2ff7f9586bf)
> Add SSH command for executions 

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- Makefile
- pyproject.toml
- requirements-test.txt
- valohai_cli/commands/yaml/pipeline.py
* Ensure that users get new versions of transitive deps
* Upgrade lint tools & fix things so they don't complain
* Speed up CI by using `uv`
* Fix Codecov reporting (token was missing; that had worked before, not so anymore)
> Dependency upgrades & minor CI renovation

- tests/commands/execution/test_run.py
- valohai_cli/commands/execution/run/dynamic_run_command.py
- valohai_cli/commands/execution/run/frontend_command.py
Resolves [valohai/roi#8352
](https://github.com/valohai/roi/issues/8352) (`time_limit` not passed to execution via CLI)
The `time-limit` setting is parsed and included in the execution parameters if it is set
(0 = no time limit, so it is not included in the params).
> 🩹 Pass time-limit YAML setting to execution

- tests/commands/pipeline/test_run.py
- tests/commands/run_test_utils.py
- tests/fixture_data.py
- tests/utils.py
- valohai_cli/commands/pipeline/run/run.py
Allow setting `--environment` when creating pipelines; it adds/replaces the `environment` value in each node's `template`.
> Allow overriding node environments when starting a pipeline

- valohai_cli/api.py
- valohai_cli/commands/execution/outputs.py
This is required for certain private server configurations.
> Handle 'Content-Disposition: attachment' when downloading outputs

- .github/workflows/ci.yml
- pyproject.toml
Click v8.2 introduces some changes that break tests, especially where git operations are monkeypatched: it produces the following extra warning output:
```
Warning: The directory is not a Git repository. 
Would you like to just run using the latest commit known by Valohai?
Use latest commit? [Y/n]:Aborted!
```
Naturally, this breaks the tests that check the output for expected test.
Temporarily fixed by pinning `click` to a version below `8.2`.
---
Also update `setup-uv` to `v6` while at it (unrelated, but left there since it was already there due to earlier testing).
> Pin Click to latest version that does not break tests

- README.md
Make the list of supported Python versions more readable by formatting it as an actual list.
This PR was originally just a confirmation that the test issue (fixed in #336) was caused by the CI environment and not code changes. But why not improve the docs while we’re at it!
> 📝 Format list of supported Python versions as a list

- tests/commands/notebook/test_notebook_execution_run.py
- valohai_cli/commands/notebook/run/run.py
- valohai_cli/consts.py
If no environment is explicitly specified, instruct the API to use the project default environment.
Works with Roi `20250604.103429Z-93db42506` or newer.
Resolves #342
> ✨ Make the `--environment` parameter optional

- valohai_cli/cli.py
The purpose of this option is to make it easier to check which version of valohai-cli you are using (e.g. when debugging stuff).
Usage:
```shell
$ vh --version
vh 0.33.0
```
> ✨ Add `--version` option to the `vh` command

- DEVELOPMENT.md
- README.md
In preparation for dropping Python 3.8 support in the next release, update the README version history for Python support, plus the current version in the dev readme.
No changelog update at this point – that should be done when preparing the next release.
> 📝 Update Python version in docs
